# Generated by Django 3.2.8 on 2021-10-09 17:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('cursos', '0002_aula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('aula', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='cursos.aula')),
                ('usuario', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='usuarios.usuario')),
            ],
        ),
    ]
